# Voorbeeldconfiguratie voor aeron-imgman

database:
  host: localhost
  port: 5432
  name: aeron_db
  user: aeron_user
  password: aeron_password
  schema: aeron
  sslmode: disable

image:
  # Dit is hoe groot de afbeeldingen in de DB komen
  target_width: 640
  target_height: 640
  
  # JPEG-kwaliteit (1-100)
  quality: 90
  
  # Gebruik Google's moderne Jpegli encoder voor betere compressie
  use_jpegli: true
  
  # Maximale bestandsgrootte van bronbestand
  max_file_size_mb: 20
  
  # Verwerkingsgedrag
  reject_smaller: true
