# Voorbeeld configuratie voor aeron-imgbatch

# Database Configuratie
database:
  host: localhost
  port: 5432
  name: aeron_db
  user: aeron_user
  password: aeron_password
  schema: aeron
  sslmode: disable

# Afbeelding Verwerkings Configuratie
image:
  # Doel afbeelding afmetingen
  target_width: 640
  target_height: 640
  
  # JPEG kwaliteit (1-100)
  quality: 90
  
  # Gebruik Jpegli encoder voor betere compressie
  use_jpegli: true
  
  # Maximale bestandsgrootte in MB
  max_file_size_mb: 20
  
  # Verwerkings gedrag
  reject_smaller: true    # Weiger afbeeldingen kleiner dan doelgrootte
  
  # Opmerking: Grotere afbeeldingen worden altijd verkleind naar doelafmetingen
  # Ondersteunde formaten: JPG, JPEG, PNG (altijd toegestaan)