# Voorbeeldconfiguratie voor aeron-imgman

database:
  host: localhost
  port: 5432
  name: aeron_db
  user: aeron_user
  password: aeron_password
  schema: aeron
  sslmode: disable

image:
  # Dit is hoe groot de afbeeldingen in de DB komen
  target_width: 1280
  target_height: 1280
  
  # JPEG-kwaliteit (1-100)
  quality: 90
  
  # Maximale bestandsgrootte van bronbestand
  max_file_size_mb: 200
  
  # Verwerkingsgedrag
  reject_smaller: true
