# Voorbeeldconfiguratie voor aeron-imgman

database:
  host: localhost
  port: 5413
  name: aeron_prod_db
  user: aeron_dba
  password: aeron_dba
  schema: aeron
  sslmode: disable

image:
  # Dit is hoe groot de afbeeldingen in de DB komen
  target_width: 640
  target_height: 640
  
  # JPEG-kwaliteit (1-100)
  quality: 90
  
  # Maximale bestandsgrootte van bronbestand
  max_file_size_mb: 200
  
  # Verwerkingsgedrag
  reject_smaller: true
